permalink: /:title/

exclude: ["_wp", "scss", "README.md", "config.rb", "_inspect.rb"]

title: My notes
tagline: hello world
author:
    name: Marchenko Alexandr
    email: marchenko.alexandr@gmail.com
    github: mac2000
    twitter: alexandrm

