permalink: /:title/
safe: true
lsi: false
timezone: Europe/Kiev
encoding: utf-8
markdown: kramdown
title: My notes
production_url: https://mac-blog.org.ua
author:
    name: Marchenko Alexandr
    email: marchenko.alexandr@gmail.com
    github: mac2000
    twitter: alexandrm

