permalink: /:title/
safe: true
exclude: ["scss", "README.md", "config.rb", "_inspect.rb"]

title: My notes
production_url: http://mac-blog.org.ua
author:
    name: Marchenko Alexandr
    email: marchenko.alexandr@gmail.com
    github: mac2000
    twitter: alexandrm

