permalink: /:title/

exclude: ["_wp", "scss", "README.md", "config.rb"]
markdown: redcarpet2
redcarpet:
    extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolinks", "tables"]

title: My notes
tagline: hello world
author:
    name: Marchenko Alexandr
    email: marchenko.alexandr@gmail.com
    github: mac2000
    twitter: alexandrm

