permalink: /:title/
safe: true
lsi: false
pygments: false
markdown: kramdown
exclude: ["scss", "README.md", "config.rb"]

title: My notes
production_url: http://mac-blog.org.ua
author:
    name: Marchenko Alexandr
    email: marchenko.alexandr@gmail.com
    github: mac2000
    twitter: alexandrm

